name: Release Go modules
on:
  create:
    # Trigger the workflow when a new tag is created
    tags:
      # Limit the triggering to tags that match the given pattern
      - '@siafoundation/(renterd|hostd|walletd)@*.*.*'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency: commit-group

jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 16
      - name: Set variables
        shell: bash
        run: |
          NAME=$(echo "${{ github.ref }}" | sed -E 's/^refs\/tags\/@siafoundation\/(.*)@.*$/\1/')
          VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/tags\/@siafoundation\/.*@(.*)$/\1/')
          TAG="${NAME}/${VERSION}"
          echo "NAME=${NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Next export
        shell: bash
        run: |
          npx nx export $NAME
      # - name: Checkout a branch
      #   run: |
      #     git checkout -b release-go ${{ github.ref }}
      - name: Copy files
        run: |
          mkdir -p ${NAME}/assets
          rm -rf ${NAME}/assets/*
          cp -R dist/apps/${NAME}/exported/* ${NAME}/assets/
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: release Go modules"
      - name: Create tag
        run: |
          git tag ${TAG}
      - name: Push changes
        run: |
          git checkout -b release ${TAG}
          git fetch origin main
          git rebase origin/main
          git checkout main
          git merge --ff-only release
          git push origin main
          git push origin ${TAG} main
          git branch -D release
