name: Release Go modules

concurrency: commits-to-main

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 16
      - name: Release
        run: ./scripts/release-go.sh
